# Generated by Django 3.0.3 on 2020-11-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog_post',
            unique_together=set(),
        ),
    ]
