# Generated by Django 3.0.3 on 2020-10-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_education_level_employment_detail_file_uploaded_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
