# Generated by Django 3.0.3 on 2020-11-16 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+254999999999'.Upto 15 digits allowed", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
